### ISSUE TITLE
Hash collision?

### ISSUE THREAD

**Issue by icexin** [mndrix/ps#1]
In map, hash code may collison, then different key with same hash code can be overrided。
Is it on purpose or something else?

**Comment by mndrix** [comment]
This behavior was intentional.  With a 64-bit hash key, one must have about 10^5 keys in a map before the [probability of a collision](https://en.wikipedia.org/wiki/Birthday_problem#Probability_table) approaches the probability of winning a Powerball lottery.  My original use cases only needed about 10^3 keys so I wasn't concerned about collisions.

However, this library has become more popular since I first released it.  I realize that other users may want larger maps.  For them a collision may be a problem.  I'll push a commit which converts a hash collision into a panic with instructions to report the details here.  If hash collisions are a problem in the real world, this will make it apparent.  At that point, we'll know it's a real problem and have a test case to work with.

Thanks for the report @icexin

**Comment by icexin** [comment]
Thanks for you reply. 
I make a benchmark among some `persist map` implementation, this implementation has the best performance。
So I wish it could also work correctly in the real world. :)

**Comment by mndrix** [comment]
> So I wish it could also work correctly in the real world. :)

:-) It works fine in the real world, but no software package is right for every use case.

If you can provide me a failing test from a real world scenario where a hash collision is a problem, I'll gladly consider fixing it.

**Comment by icexin** [comment]
OK,  I will keep an eye on it. Thank you!
